# kompilator c
CCOMP = mpicc

# konsolidator
LOADER = mpicc

# program uruchomieniowy MPI
MPI_run = mpiexec -oversubscribe

# opcje optymalizacji:
# wersja do debugowania
OPT = -g -DDEBUG
# wersja zoptymalizowana do mierzenia czasu
# OPT = -O3

# pliki naglowkowe
#INC = -I../pomiar_czasu

# biblioteki
#LIB = -L../pomiar_czasu -lm
LIB = -lm

all: MPI_relay run

run: MPI_relay
        $(MPI_run) -np 5 ./MPI_relay

# zaleznosci i komendy
MPI_relay : MPI_relay.o
        $(LOADER) $(OPT) MPI_relay.o -o MPI_relay $(LIB)

# jak uzyskac plik moj_program.o ?
MPI_relay.o: MPI_relay.c
        $(CCOMP) -c $(OPT) MPI_relay.c

clean:
        rm -f *.o MPI_relay



